name: Build & Validate
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python -m src.cli build
      - run: python -m src.cli validate-rdf
      - run: python -m src.cli validate-shacl
      - run: pytest -q
